### ISSUE TITLE
Could this get expensive since the cloud function has to boot up sapper each time its ran?

### ISSUE THREAD

**Issue by quantuminformation** [tristolliday/sapper-firebase-sample#1]

**Comment by tristolliday** [comment]
It would depend on how many times the function ran, but currently you can have up to 2M free invocations a month, which should be more than ample for most projects. It's also worth noting that Sapper isn't necessarily the best option for a production set up due to it still being early days. 

Svelte are already looking at moving the project into SvelteKit, and Rich Harris has said Sapper will never get to 1.0.0 (https://svelte.dev/blog/whats-the-deal-with-sveltekit).

If you were looking to use Sapper for production, I would recommend looking into the export flag, that builds an entirely static version of your site, so long as you don't need any authentication or dynamic content.
